/* explorers.js — Explorers and their abilities for Sub Terra II */

export const ABILITIES = {
  scholar: {
    id: 'scholar',
    name: 'Érudite',
    cost: 0,
    passive: true,
    uses: null,
    description: 'Au lieu de piocher une tuile, piochez-en deux, choisissez-en une et remettez l\'autre dans le sac.',
  },
  adventurer: {
    id: 'adventurer',
    name: 'Aventurière',
    cost: 1,
    costType: 'hp',
    passive: false,
    uses: null,
    description: 'Dépensez 1 PV pour relancer n\'importe quel dé.',
  },
  agile: {
    id: 'agile',
    name: 'Agile',
    cost: 0,
    passive: true,
    uses: null,
    description: 'Lors de Se déplacer, Courir ou Explorer, ignorez les marqueurs Éboulis.',
  },
  illuminate: {
    id: 'illuminate',
    name: 'Illuminer',
    cost: 1,
    passive: false,
    uses: null,
    description: 'Effectuez deux fois l\'action Révéler.',
  },
  sprint: {
    id: 'sprint',
    name: 'Sprinter',
    cost: 1,
    passive: false,
    uses: null,
    description: 'Effectuez deux fois l\'action Se déplacer.',
  },
  vigilance: {
    id: 'vigilance',
    name: 'Vigilance',
    cost: 0,
    passive: true,
    uses: null,
    description: 'Vous et les Explorateurs sur votre tuile ne déclenchez pas de piège et ne perdez pas de PV de piège.',
  },
  order: {
    id: 'order',
    name: 'Ordonner',
    cost: 1,
    passive: false,
    uses: null,
    description: 'Choisissez un Explorateur non à terre : il effectue immédiatement une action Se déplacer.',
  },
  research: {
    id: 'research',
    name: 'Rechercher',
    cost: 1,
    passive: false,
    uses: 3,
    description: 'Placez une tuile Journal connectée à n\'importe quelle tuile du Temple. (3 fois)',
  },
  excavate: {
    id: 'excavate',
    name: 'Excaver',
    cost: 1,
    passive: false,
    uses: null,
    description: 'Effectuez une action Creuser.',
  },
  consolidate: {
    id: 'consolidate',
    name: 'Consolider',
    cost: 1,
    passive: false,
    uses: 4,
    description: 'Placez un marqueur Consolidation sur votre tuile : elle devient normale à vie. (4 fois)',
  },
  scope: {
    id: 'scope',
    name: 'Lunette de visée',
    cost: 1,
    passive: false,
    uses: null,
    description: 'Révélez une tuile visible en ligne droite, à 3 tuiles ou moins.',
  },
  snipe: {
    id: 'snipe',
    name: 'Tir de précision',
    cost: 1,
    passive: false,
    uses: null,
    description: 'Éliminez un ennemi visible en ligne droite à ≤3 tuiles (pas sur votre tuile).',
  },
  grenade: {
    id: 'grenade',
    name: 'Grenade',
    cost: 1,
    passive: false,
    uses: null,
    description: 'Éliminez tous les ennemis sur une tuile adjacente connectée. Les Explorateurs sur cette tuile perdent 1 PV.',
  },
  demolish: {
    id: 'demolish',
    name: 'Démolir',
    cost: 1,
    passive: false,
    uses: 3,
    description: 'Détruisez un mur adjacent. Placez un marqueur Démolition. (3 fois)',
  },
  annihilate: {
    id: 'annihilate',
    name: 'Anéantir',
    cost: 1,
    passive: false,
    uses: null,
    description: 'Éliminez un ennemi situé sur votre tuile.',
  },
  prepare: {
    id: 'prepare',
    name: 'Se préparer',
    cost: 1,
    passive: false,
    uses: null,
    description: 'Impossible de perdre de PV jusqu\'à votre prochain tour. (Se dépasser coûte toujours 1 PV)',
  },
  heal: {
    id: 'heal',
    name: 'Guérir',
    cost: 1,
    passive: false,
    uses: null,
    description: 'Un Explorateur visible à ≤2 tuiles récupère 2 PV.',
  },
  survivor: {
    id: 'survivor',
    name: 'Survivante',
    cost: 0,
    passive: true,
    uses: null,
    description: 'Sur un résultat Trébucher au dé de Péril, regagnez 1 PV au lieu de l\'effet habituel.',
  },
  revive: {
    id: 'revive',
    name: 'Ranimer',
    cost: 1,
    passive: false,
    uses: null,
    description: 'Choisissez un autre Explorateur : s\'il est à terre, +1 PV ; sinon +3 PV.',
  },
  purify: {
    id: 'purify',
    name: 'Purifier',
    cost: 1,
    passive: false,
    uses: null,
    description: 'Choisissez une autre tuile : éliminez tous les ennemis qui s\'y trouvent.',
  },
};

export const EXPLORERS = [
  {
    id: 'aristocrat',
    name: "L'Aristocrate",
    role: 'Exploration',
    pv: 3,
    color: '#d4af37',
    glyph: 'A',
    abilities: ['scholar', 'adventurer'],
    blurb: "L'Aristocrate utilise son érudition pour explorer plus efficacement et n'hésite pas à sacrifier sa vitalité.",
  },
  {
    id: 'thief',
    name: 'Le Gredin',
    role: 'Exploration',
    pv: 3,
    color: '#2e7d32',
    glyph: 'G',
    abilities: ['agile', 'illuminate'],
    blurb: 'Le Gredin se faufile sans encombre et révèle les ténèbres.',
  },
  {
    id: 'scout',
    name: 'Le Guide',
    role: 'Exploration',
    pv: 5,
    color: '#1565c0',
    glyph: 'U',
    abilities: ['sprint', 'vigilance'],
    blurb: 'Le Guide fend la voie et protège ses compagnons des pièges.',
  },
  {
    id: 'commander',
    name: "L'Archéo",
    role: 'Commandement',
    pv: 5,
    color: '#8d6e63',
    glyph: 'R',
    abilities: ['order', 'research'],
    blurb: "L'Archéo coordonne l'équipe et déniche les précieux journaux.",
  },
  {
    id: 'miner',
    name: 'Le Contremaître',
    role: 'Force',
    pv: 7,
    color: '#ef6c00',
    glyph: 'C',
    abilities: ['excavate', 'consolidate'],
    blurb: 'Le Contremaître creuse et consolide les passages instables.',
  },
  {
    id: 'sniper',
    name: "Le Tireur d'élite",
    role: 'Combat',
    pv: 5,
    color: '#6a1b9a',
    glyph: 'T',
    abilities: ['scope', 'snipe'],
    blurb: "Le Tireur d'élite repère et abat les ennemis à distance.",
  },
  {
    id: 'sapper',
    name: 'Le Sapeur',
    role: 'Combat',
    pv: 5,
    color: '#bf360c',
    glyph: 'S',
    abilities: ['grenade', 'demolish'],
    blurb: 'Le Sapeur fait sauter les obstacles et les groupes d\'ennemis.',
  },
  {
    id: 'soldier',
    name: 'La Combattante',
    role: 'Combat',
    pv: 7,
    color: '#c62828',
    glyph: 'M',
    abilities: ['annihilate', 'prepare'],
    blurb: 'La Combattante écrase les ennemis au corps-à-corps et encaisse les coups.',
  },
  {
    id: 'nurse',
    name: 'La Guérisseuse',
    role: 'Soin',
    pv: 5,
    color: '#43a047',
    glyph: 'H',
    abilities: ['heal', 'survivor'],
    blurb: 'La Guérisseuse soigne les blessures et résiste aux chutes.',
  },
  {
    id: 'priestess',
    name: 'Le Prêtre',
    role: 'Soin',
    pv: 3,
    color: '#fdd835',
    glyph: 'P',
    abilities: ['revive', 'purify'],
    blurb: 'Le Prêtre ranime les tombés et purifie les lieux corrompus.',
  },
];
